# Generated by Django 5.0.7 on 2024-12-07 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('IRANI', 'Irani'), ('MOUNTAGE', 'Mountage'), ('VAREDATI', 'Varedati'), ('HYBRID', 'Hybrid'), ('EV', 'EV')], default='IRANI', max_length=50)),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('sub_model', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='City Name')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='expert_icons/')),
            ],
            options={
                'verbose_name': 'Expert',
                'verbose_name_plural': 'Experts',
            },
        ),
        migrations.CreateModel(
            name='SPCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Category Name')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='SPCategory_icons/')),
            ],
            options={
                'verbose_name': 'Service Provider Category',
                'verbose_name_plural': 'Service Provider Categories',
            },
        ),
        migrations.CreateModel(
            name='TagKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tag Key',
                'verbose_name_plural': 'Tag Keys',
            },
        ),
        migrations.CreateModel(
            name='Weekday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Weekday',
                'verbose_name_plural': 'Weekdays',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=255)),
                ('neighbourhood', models.CharField(max_length=150)),
                ('full_address', models.CharField(max_length=255, verbose_name='Full Address')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='service_provider.city', verbose_name='City')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo_image', models.ImageField(upload_to='SP_logos/')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='SP_main_images/')),
                ('location', models.CharField(max_length=255)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service_provider.address')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service_provider.spcategory')),
            ],
            options={
                'verbose_name': 'Service Provider',
                'verbose_name_plural': 'Service Providers',
            },
        ),
        migrations.CreateModel(
            name='SPCarExpert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_provider.serviceprovider')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_provider.car')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_provider.expert')),
            ],
            options={
                'verbose_name': 'Service Provider Car Expertise',
                'verbose_name_plural': 'Service Provider Car Expertises',
            },
        ),
        migrations.CreateModel(
            name='SPExpert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('SP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expertises', to='service_provider.serviceprovider')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SPs', to='service_provider.expert')),
            ],
            options={
                'verbose_name': 'Service Provider Expertise',
                'verbose_name_plural': 'Service Provider Expertises',
            },
        ),
        migrations.CreateModel(
            name='SPImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='SP_images/')),
                ('SP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='service_provider.serviceprovider')),
            ],
            options={
                'verbose_name': 'Service Provider Image',
                'verbose_name_plural': 'Service Provider Images',
            },
        ),
        migrations.CreateModel(
            name='SPOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Provider Owner',
                'verbose_name_plural': 'Service Provider Owners',
            },
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_provider.spowner'),
        ),
        migrations.CreateModel(
            name='SPRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('SP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='service_provider.serviceprovider')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Provider Rating',
                'verbose_name_plural': 'Service Provider Ratings',
            },
        ),
        migrations.CreateModel(
            name='SPReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('SP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='service_provider.serviceprovider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Provider Review',
                'verbose_name_plural': 'Service Provider Reviews',
            },
        ),
        migrations.CreateModel(
            name='SPWorkTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('SP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_times', to='service_provider.serviceprovider')),
                ('weekday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_provider.weekday')),
            ],
            options={
                'verbose_name': 'Service Provider Work Time',
                'verbose_name_plural': 'Service Provider Work Times',
            },
        ),
        migrations.CreateModel(
            name='SPTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('SP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='service_provider.serviceprovider')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SP_tags', to='service_provider.tagkey')),
            ],
            options={
                'verbose_name': 'Service Provider Tag',
                'verbose_name_plural': 'Service Provider Tags',
                'unique_together': {('SP', 'key', 'value')},
            },
        ),
    ]
