# Generated by Django 5.0.7 on 2024-12-20 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0002_carcategory_remove_car_tag_car_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gifts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='expert',
            name='spcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expertise', to='service_provider.spcategory'),
        ),
        migrations.CreateModel(
            name='SPGifts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amout', models.FloatField()),
                ('gift_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_provider.gifts')),
                ('sp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_provider.serviceprovider')),
            ],
        ),
    ]
