# Generated by Django 5.0.7 on 2024-12-22 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0003_gifts_expert_spcategory_spgifts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spgifts',
            options={'verbose_name': 'Service Provider Gift', 'verbose_name_plural': 'Service Provider Gifts'},
        ),
        migrations.RenameField(
            model_name='spgifts',
            old_name='amout',
            new_name='amount',
        ),
    ]
